//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clients.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sendMsg", ReplyAction="http://tempuri.org/IService1/sendMsgResponse")]
        void sendMsg(string senderID, string receiverID, string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sendMsg", ReplyAction="http://tempuri.org/IService1/sendMsgResponse")]
        System.Threading.Tasks.Task sendMsgAsync(string senderID, string receiverID, string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/receiveMsg", ReplyAction="http://tempuri.org/IService1/receiveMsgResponse")]
        string[] receiveMsg(string receiverID, bool purge);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/receiveMsg", ReplyAction="http://tempuri.org/IService1/receiveMsgResponse")]
        System.Threading.Tasks.Task<string[]> receiveMsgAsync(string receiverID, bool purge);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Clients.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Clients.ServiceReference1.IService1>, Clients.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void sendMsg(string senderID, string receiverID, string msg) {
            base.Channel.sendMsg(senderID, receiverID, msg);
        }
        
        public System.Threading.Tasks.Task sendMsgAsync(string senderID, string receiverID, string msg) {
            return base.Channel.sendMsgAsync(senderID, receiverID, msg);
        }
        
        public string[] receiveMsg(string receiverID, bool purge) {
            return base.Channel.receiveMsg(receiverID, purge);
        }
        
        public System.Threading.Tasks.Task<string[]> receiveMsgAsync(string receiverID, bool purge) {
            return base.Channel.receiveMsgAsync(receiverID, purge);
        }
    }
}
