//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowConsoleApplication1.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRandomString0", ReplyAction="http://tempuri.org/IService/GetRandomString0Response")]
        WorkflowConsoleApplication1.ServiceReference2.GetRandomString0Response GetRandomString0(WorkflowConsoleApplication1.ServiceReference2.GetRandomString0Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRandomString0", ReplyAction="http://tempuri.org/IService/GetRandomString0Response")]
        System.Threading.Tasks.Task<WorkflowConsoleApplication1.ServiceReference2.GetRandomString0Response> GetRandomString0Async(WorkflowConsoleApplication1.ServiceReference2.GetRandomString0Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRandomString", ReplyAction="http://tempuri.org/IService/GetRandomStringResponse")]
        WorkflowConsoleApplication1.ServiceReference2.GetRandomStringResponse GetRandomString(WorkflowConsoleApplication1.ServiceReference2.GetRandomStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRandomString", ReplyAction="http://tempuri.org/IService/GetRandomStringResponse")]
        System.Threading.Tasks.Task<WorkflowConsoleApplication1.ServiceReference2.GetRandomStringResponse> GetRandomStringAsync(WorkflowConsoleApplication1.ServiceReference2.GetRandomStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRandomString3", ReplyAction="http://tempuri.org/IService/GetRandomString3Response")]
        WorkflowConsoleApplication1.ServiceReference2.GetRandomString3Response GetRandomString3(WorkflowConsoleApplication1.ServiceReference2.GetRandomString3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetRandomString3", ReplyAction="http://tempuri.org/IService/GetRandomString3Response")]
        System.Threading.Tasks.Task<WorkflowConsoleApplication1.ServiceReference2.GetRandomString3Response> GetRandomString3Async(WorkflowConsoleApplication1.ServiceReference2.GetRandomString3Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRandomString0", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRandomString0Request {
        
        public GetRandomString0Request() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRandomString0Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRandomString0Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetRandomString0Result;
        
        public GetRandomString0Response() {
        }
        
        public GetRandomString0Response(string GetRandomString0Result) {
            this.GetRandomString0Result = GetRandomString0Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRandomString", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRandomStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Length;
        
        public GetRandomStringRequest() {
        }
        
        public GetRandomStringRequest(string Length) {
            this.Length = Length;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRandomStringResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRandomStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetRandomStringResult;
        
        public GetRandomStringResponse() {
        }
        
        public GetRandomStringResponse(string GetRandomStringResult) {
            this.GetRandomStringResult = GetRandomStringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRandomString3", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRandomString3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Length;
        
        public GetRandomString3Request() {
        }
        
        public GetRandomString3Request(string Length) {
            this.Length = Length;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRandomString3Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRandomString3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetRandomString3Result;
        
        public GetRandomString3Response() {
        }
        
        public GetRandomString3Response(string GetRandomString3Result) {
            this.GetRandomString3Result = GetRandomString3Result;
        }
    }
}
